import React, { useState } from "react";
import { TimeCard } from "components";
import Head from "next/head";
import { Box } from "theme-ui";

import data from "data/data";

export default function Home() {
  const [timeframe] = useState("daily");

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <Box as="main" sx={{ margin: "2em" }}>
        {data.map(({ title, timeframes }) => (
          <TimeCard
            title={title}
            current={timeframes[timeframe].current}
            previous={timeframes[timeframe].previous}
          />
        ))}
      </Box>
    </div>
  );
}
